name: ClusterFuzzLite PR fuzzing

on:
  pull_request:
    paths:
      - src/**
      - tests/fuzz/**
      - .clusterfuzzlite/**
      - .github/workflows/cflite_pr.yml

permissions: read-all

jobs:
  PR:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address]
    steps:
      - name: Build Fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          sanitizer: ${{ matrix.sanitizer }}
          language: python
      - name: Run Fuzzers
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 180
          mode: "code-change"
          report-unreproducible-crashes: false
          sanitizer: ${{ matrix.sanitizer }}
          language: python
